In [38]:
import xarray as xr
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from constants import MJO_DATA_PATH

In [39]:
MJO_DATA_PATH

'/g/data/w40/ab2313/mjo_and_rainfall_trend'

In [40]:
os.listdir(MJO_DATA_PATH)

['awap_sub.nc',
 'precip_calib_0.25_1911_2017_land.nc',
 'awap_n3.nc',
 'awap_grid.grd',
 'awap_n4.nc',
 'awap_n2.nc',
 'mjoindex_IHR_OT12.nc',
 'mjoindex_IHR_20CRV2c.nc',
 'rmm.csv',
 'agcd_v1_precip_calib_r005_daily_2020.nc',
 'awap_n.nc',
 'awap_2',
 'precip_calib_0.25_maskforCAus.nc']

# AWAP

In [41]:
awap_n4 = xr.open_dataset(os.path.join(MJO_DATA_PATH, 'awap_n4.nc'))

In [42]:
np.unique(awap_n4.time.dt.year)

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [48]:
awap = xr.open_dataset(os.path.join(MJO_DATA_PATH, 'precip_calib_0.25_1911_2017_land.nc'))

In [50]:
np.unique(awap.time.dt.year)

array([1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017])

# RMM

In [44]:
rmm_oliver = xr.open_dataset(os.path.join(MJO_DATA_PATH, 'mjoindex_IHR_20CRV2c.nc'))
rmm_oliver

<xarray.Dataset>
Dimensions:    (time: 40177)
Dimensions without coordinates: time
Data variables:
    t_IHR      (time) float32 ...
    IHR1       (time) float32 ...
    IHR2       (time) float32 ...
    IHR_amp    (time) float32 ...
    IHR_phase  (time) float32 ...
Attributes:
    description:  Reconstructed MJO Index (1905-2014)
    author:       Eric Oliver, Ph.D., Dalhousie University
    date:         2016-Nov-04 14:28:34
    File_Name:    data/mjoindex_IHR.nc
    Title:        Reconstructed MJO Index (1905-2014)
    Source_File:

In [51]:
rmm_oliver['time'] = xr.cftime_range(start = '1905-01-01', periods = len(rmm_oliver.time), freq='D')

In [56]:
rmm_oliver.rename({'IHR_amp':'amplitude', 'IHR_phase': 'phase', 'IHR1': 'RMM1', 'IHR2': 'RMM2'})

<xarray.Dataset>
Dimensions:    (time: 40177)
Coordinates:
  * time       (time) object 1905-01-01 00:00:00 ... 2014-12-31 00:00:00
Data variables:
    t_IHR      (time) float32 6.958e+05 6.958e+05 ... 7.36e+05 7.36e+05
    RMM1       (time) float32 -0.3303 -0.3193 -0.3354 ... 1.329 1.27 0.8695
    RMM2       (time) float32 1.142 1.288 1.432 1.526 ... -0.3652 -0.1545 0.3881
    amplitude  (time) float32 1.189 1.327 1.471 1.572 ... 1.378 1.279 0.9522
    phase      (time) float32 7.0 7.0 7.0 7.0 7.0 7.0 ... 4.0 4.0 4.0 4.0 5.0
Attributes:
    description:  Reconstructed MJO Index (1905-2014)
    author:       Eric Oliver, Ph.D., Dalhousie University
    date:         2016-Nov-04 14:28:34
    File_Name:    data/mjoindex_IHR.nc
    Title:        Reconstructed MJO Index (1905-2014)
    Source_File:

In [23]:
rmm_oliver.IHR_amp

<xarray.DataArray 'IHR_amp' (time: 40177)>
array([1.1885  , 1.326611, 1.470823, ..., 1.378055, 1.279328, 0.952187],
      dtype=float32)
Dimensions without coordinates: time
Attributes:
    units:      unitless
    title:      MJO index amplitude)
    valid_min:  0.007002300559996748
    valid_max:  4.911123149288893

In [26]:
rmm_oliver.time

<xarray.DataArray 'time' (time: 40177)>
array([    0,     1,     2, ..., 40174, 40175, 40176])
Dimensions without coordinates: time

In [28]:
rmm_oliver.t_IHR

<xarray.DataArray 't_IHR' (time: 40177)>
array([695788., 695789., 695790., ..., 735962., 735963., 735964.],
      dtype=float32)
Dimensions without coordinates: time
Attributes:
    units:      days starting on Jan-1-0000 (matlab datenum format)
    title:      Time
    long_name:  Time axis
    valid_min:  0.0
    valid_max:  735964.0

In [33]:
xr.cftime_range(start = '1905-01-01', periods = len(rmm_oliver.time), freq='D')

CFTimeIndex([1905-01-01 00:00:00, 1905-01-02 00:00:00, 1905-01-03 00:00:00,
             1905-01-04 00:00:00, 1905-01-05 00:00:00, 1905-01-06 00:00:00,
             1905-01-07 00:00:00, 1905-01-08 00:00:00, 1905-01-09 00:00:00,
             1905-01-10 00:00:00,
             ...
             2014-12-22 00:00:00, 2014-12-23 00:00:00, 2014-12-24 00:00:00,
             2014-12-25 00:00:00, 2014-12-26 00:00:00, 2014-12-27 00:00:00,
             2014-12-28 00:00:00, 2014-12-29 00:00:00, 2014-12-30 00:00:00,
             2014-12-31 00:00:00],
            dtype='object', length=40177, calendar='gregorian', freq='D')